import { Event } from '../helpers/types';

export const fakeEvents: Event[] = [
  {
    type: 'Question-answer',
    title: 'Introduction to AI',
    description: 'Essentials for launching a successful startup.',
    startOn: '2024-11-25 00:00:00',
    location: 'New York, Highland Ave',
  },
  {
    type: 'Meeting with an expert',
    title: 'Introduction to AI',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2024-11-25 00:00:00',
    location: 'Chicago, Highland Ave',
  },
  {
    type: 'Webinar',
    title: 'Networking Event',
    description: 'A networking event to meet industry experts.',
    startOn: '2024-11-25 00:00:00',
    location: 'Chicago, Highland Ave',
  },
  {
    type: 'Meeting with an expert',
    title: 'Startup Essentials',
    description: 'Learn about the latest in AI technology.',
    startOn: '2024-11-04 00:00:00',
    location: 'Los Angeles, Highland Ave',
  },
  {
    type: 'Webinar',
    title: 'Networking Event',
    description: 'Essentials for launching a successful startup.',
    startOn: '2024-11-20 00:00:00',
    location: 'Houston, Broadway',
  },
  {
    type: 'Webinar',
    title: 'Tech Trends 2024',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2024-11-12 00:00:00',
    location: 'Miami, Elm St',
  },
  {
    type: 'Conference',
    title: 'Networking Event',
    description: 'Learn about the latest in AI technology.',
    startOn: '2024-11-08 00:00:00',
    location: 'Houston, Elm St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Tech Trends 2024',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2024-11-01 00:00:00',
    location: 'Houston, Maple Ave',
  },
  {
    type: 'Conference',
    title: 'Networking Event',
    description: 'A networking event to meet industry experts.',
    startOn: '2024-11-21 00:00:00',
    location: 'Chicago, Elm St',
  },
  {
    type: 'Question-answer',
    title: 'Startup Essentials',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2024-11-20 00:00:00',
    location: 'Chicago, Broadway',
  },
  {
    type: 'Webinar',
    title: 'Startup Essentials',
    description: 'A networking event to meet industry experts.',
    startOn: '2024-12-03 00:00:00',
    location: 'Houston, Elm St',
  },
  {
    type: 'Webinar',
    title: 'Startup Essentials',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2024-12-10 00:00:00',
    location: 'Chicago, Maple Ave',
  },
  {
    type: 'Webinar',
    title: 'Tech Trends 2024',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2024-12-26 00:00:00',
    location: 'Los Angeles, Maple Ave',
  },
  {
    type: 'Question-answer',
    title: 'Networking Event',
    description: 'Essentials for launching a successful startup.',
    startOn: '2024-12-04 00:00:00',
    location: 'Chicago, Maple Ave',
  },
  {
    type: 'Conference',
    title: 'Tech Trends 2024',
    description: 'Essentials for launching a successful startup.',
    startOn: '2024-12-02 00:00:00',
    location: 'Los Angeles, Main St',
  },
  {
    type: 'Webinar',
    title: 'Tech Trends 2024',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2024-12-26 00:00:00',
    location: 'Miami, Elm St',
  },
  {
    type: 'Webinar',
    title: 'Startup Essentials',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2024-12-21 00:00:00',
    location: 'Houston, Elm St',
  },
  {
    type: 'Question-answer',
    title: 'Startup Essentials',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2024-12-07 00:00:00',
    location: 'Miami, Elm St',
  },
  {
    type: 'Webinar',
    title: 'Startup Essentials',
    description: 'Learn about the latest in AI technology.',
    startOn: '2024-12-16 00:00:00',
    location: 'Chicago, Main St',
  },
  {
    type: 'Webinar',
    title: 'Tech Trends 2024',
    description: 'Learn about the latest in AI technology.',
    startOn: '2024-12-11 00:00:00',
    location: 'New York, Elm St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Networking Event',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2024-12-16 00:00:00',
    location: 'New York, Maple Ave',
  },
  {
    type: 'Conference',
    title: 'Tech Trends 2024',
    description: 'Essentials for launching a successful startup.',
    startOn: '2024-12-14 00:00:00',
    location: 'Miami, Broadway',
  },
  {
    type: 'Meeting with an expert',
    title: 'Introduction to AI',
    description: 'Learn about the latest in AI technology.',
    startOn: '2024-12-30 00:00:00',
    location: 'New York, Main St',
  },
  {
    type: 'Question-answer',
    title: 'Networking Event',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2024-12-20 00:00:00',
    location: 'Chicago, Broadway',
  },
  {
    type: 'Question-answer',
    title: 'Tech Trends 2024',
    description: 'Learn about the latest in AI technology.',
    startOn: '2024-12-01 00:00:00',
    location: 'New York, Elm St',
  },
  {
    type: 'Conference',
    title: 'Introduction to AI',
    description: 'A networking event to meet industry experts.',
    startOn: '2024-12-08 00:00:00',
    location: 'Houston, Maple Ave',
  },
  {
    type: 'Conference',
    title: 'Startup Essentials',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2024-12-24 00:00:00',
    location: 'Chicago, Broadway',
  },
  {
    type: 'Conference',
    title: 'Startup Essentials',
    description: 'Essentials for launching a successful startup.',
    startOn: '2024-12-10 00:00:00',
    location: 'New York, Elm St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Networking Event',
    description: 'A networking event to meet industry experts.',
    startOn: '2024-12-09 00:00:00',
    location: 'Miami, Maple Ave',
  },
  {
    type: 'Conference',
    title: 'Introduction to AI',
    description: 'Learn about the latest in AI technology.',
    startOn: '2024-12-23 00:00:00',
    location: 'New York, Broadway',
  },
  {
    type: 'Meeting with an expert',
    title: 'Networking Event',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-01-28 00:00:00',
    location: 'Los Angeles, Broadway',
  },
  {
    type: 'Webinar',
    title: 'Tech Trends 2024',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-01-30 00:00:00',
    location: 'New York, Highland Ave',
  },
  {
    type: 'Webinar',
    title: 'Networking Event',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2025-01-30 00:00:00',
    location: 'Los Angeles, Broadway',
  },
  {
    type: 'Webinar',
    title: 'Startup Essentials',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2025-01-31 00:00:00',
    location: 'Miami, Highland Ave',
  },
  {
    type: 'Webinar',
    title: 'Startup Essentials',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-01-09 00:00:00',
    location: 'Miami, Maple Ave',
  },
  {
    type: 'Webinar',
    title: 'Networking Event',
    description: 'A networking event to meet industry experts.',
    startOn: '2025-01-23 00:00:00',
    location: 'New York, Broadway',
  },
  {
    type: 'Meeting with an expert',
    title: 'Networking Event',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-01-15 00:00:00',
    location: 'Chicago, Broadway',
  },
  {
    type: 'Meeting with an expert',
    title: 'Introduction to AI',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-01-18 00:00:00',
    location: 'Houston, Highland Ave',
  },
  {
    type: 'Question-answer',
    title: 'Tech Trends 2024',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-01-14 00:00:00',
    location: 'Los Angeles, Highland Ave',
  },
  {
    type: 'Question-answer',
    title: 'Tech Trends 2024',
    description: 'A networking event to meet industry experts.',
    startOn: '2025-01-14 00:00:00',
    location: 'Miami, Elm St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Introduction to AI',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-01-04 00:00:00',
    location: 'Los Angeles, Broadway',
  },
  {
    type: 'Conference',
    title: 'Tech Trends 2024',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-01-01 00:00:00',
    location: 'Los Angeles, Elm St',
  },
  {
    type: 'Conference',
    title: 'Startup Essentials',
    description: 'A networking event to meet industry experts.',
    startOn: '2025-01-16 00:00:00',
    location: 'Miami, Elm St',
  },
  {
    type: 'Webinar',
    title: 'Data Science Workshop',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-01-29 00:00:00',
    location: 'Los Angeles, Highland Ave',
  },
  {
    type: 'Meeting with an expert',
    title: 'Introduction to AI',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-01-31 00:00:00',
    location: 'Los Angeles, Elm St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Data Science Workshop',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-01-26 00:00:00',
    location: 'Miami, Highland Ave',
  },
  {
    type: 'Conference',
    title: 'Networking Event',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-01-19 00:00:00',
    location: 'Los Angeles, Highland Ave',
  },
  {
    type: 'Conference',
    title: 'Networking Event',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2025-01-13 00:00:00',
    location: 'Houston, Elm St',
  },
  {
    type: 'Conference',
    title: 'Tech Trends 2024',
    description: 'A networking event to meet industry experts.',
    startOn: '2025-01-18 00:00:00',
    location: 'Miami, Maple Ave',
  },
  {
    type: 'Question-answer',
    title: 'Startup Essentials',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-01-28 00:00:00',
    location: 'Miami, Elm St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Tech Trends 2024',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2025-02-07 00:00:00',
    location: 'Miami, Maple Ave',
  },
  {
    type: 'Conference',
    title: 'Startup Essentials',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-02-18 00:00:00',
    location: 'Chicago, Elm St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Tech Trends 2024',
    description: 'A networking event to meet industry experts.',
    startOn: '2025-02-25 00:00:00',
    location: 'Miami, Elm St',
  },
  {
    type: 'Conference',
    title: 'Networking Event',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-02-15 00:00:00',
    location: 'Los Angeles, Broadway',
  },
  {
    type: 'Webinar',
    title: 'Networking Event',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-02-01 00:00:00',
    location: 'Los Angeles, Main St',
  },
  {
    type: 'Question-answer',
    title: 'Startup Essentials',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-02-13 00:00:00',
    location: 'Miami, Highland Ave',
  },
  {
    type: 'Meeting with an expert',
    title: 'Introduction to AI',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-02-24 00:00:00',
    location: 'Miami, Maple Ave',
  },
  {
    type: 'Webinar',
    title: 'Startup Essentials',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-02-19 00:00:00',
    location: 'Chicago, Elm St',
  },
  {
    type: 'Webinar',
    title: 'Tech Trends 2024',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-02-28 00:00:00',
    location: 'Miami, Elm St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Data Science Workshop',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-02-01 00:00:00',
    location: 'Miami, Elm St',
  },
  {
    type: 'Conference',
    title: 'Introduction to AI',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-02-15 00:00:00',
    location: 'New York, Main St',
  },
  {
    type: 'Question-answer',
    title: 'Data Science Workshop',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-03-15 00:00:00',
    location: 'Houston, Highland Ave',
  },
  {
    type: 'Conference',
    title: 'Introduction to AI',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-03-26 00:00:00',
    location: 'Chicago, Highland Ave',
  },
  {
    type: 'Conference',
    title: 'Networking Event',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-03-26 00:00:00',
    location: 'Miami, Main St',
  },
  {
    type: 'Webinar',
    title: 'Data Science Workshop',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2025-03-01 00:00:00',
    location: 'New York, Maple Ave',
  },
  {
    type: 'Webinar',
    title: 'Startup Essentials',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-03-24 00:00:00',
    location: 'Miami, Broadway',
  },
  {
    type: 'Webinar',
    title: 'Networking Event',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-03-25 00:00:00',
    location: 'Los Angeles, Elm St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Networking Event',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-03-14 00:00:00',
    location: 'Houston, Elm St',
  },
  {
    type: 'Conference',
    title: 'Networking Event',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-03-24 00:00:00',
    location: 'Chicago, Main St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Networking Event',
    description: 'A networking event to meet industry experts.',
    startOn: '2025-03-11 00:00:00',
    location: 'Chicago, Maple Ave',
  },
  {
    type: 'Webinar',
    title: 'Networking Event',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-03-17 00:00:00',
    location: 'Los Angeles, Broadway',
  },
  {
    type: 'Meeting with an expert',
    title: 'Networking Event',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-03-28 00:00:00',
    location: 'Los Angeles, Elm St',
  },
  {
    type: 'Question-answer',
    title: 'Startup Essentials',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-03-30 00:00:00',
    location: 'Chicago, Highland Ave',
  },
  {
    type: 'Conference',
    title: 'Data Science Workshop',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-03-31 00:00:00',
    location: 'Los Angeles, Maple Ave',
  },
  {
    type: 'Webinar',
    title: 'Networking Event',
    description: 'A networking event to meet industry experts.',
    startOn: '2025-03-11 00:00:00',
    location: 'Houston, Maple Ave',
  },
  {
    type: 'Webinar',
    title: 'Networking Event',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-03-04 00:00:00',
    location: 'Houston, Main St',
  },
  {
    type: 'Question-answer',
    title: 'Startup Essentials',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-03-05 00:00:00',
    location: 'Houston, Broadway',
  },
  {
    type: 'Question-answer',
    title: 'Startup Essentials',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-03-08 00:00:00',
    location: 'Los Angeles, Elm St',
  },
  {
    type: 'Webinar',
    title: 'Introduction to AI',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2025-03-13 00:00:00',
    location: 'Miami, Elm St',
  },
  {
    type: 'Question-answer',
    title: 'Networking Event',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2025-03-12 00:00:00',
    location: 'Chicago, Broadway',
  },
  {
    type: 'Conference',
    title: 'Tech Trends 2024',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-03-11 00:00:00',
    location: 'Miami, Broadway',
  },
  {
    type: 'Question-answer',
    title: 'Networking Event',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-04-25 00:00:00',
    location: 'Miami, Maple Ave',
  },
  {
    type: 'Webinar',
    title: 'Startup Essentials',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-04-28 00:00:00',
    location: 'Houston, Highland Ave',
  },
  {
    type: 'Question-answer',
    title: 'Tech Trends 2024',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-04-08 00:00:00',
    location: 'Houston, Main St',
  },
  {
    type: 'Meeting with an expert',
    title: 'Data Science Workshop',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-04-05 00:00:00',
    location: 'Houston, Maple Ave',
  },
  {
    type: 'Meeting with an expert',
    title: 'Data Science Workshop',
    description: 'A networking event to meet industry experts.',
    startOn: '2025-04-15 00:00:00',
    location: 'Miami, Broadway',
  },
  {
    type: 'Conference',
    title: 'Networking Event',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-04-25 00:00:00',
    location: 'Los Angeles, Maple Ave',
  },
  {
    type: 'Meeting with an expert',
    title: 'Tech Trends 2024',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2025-04-14 00:00:00',
    location: 'Chicago, Broadway',
  },
  {
    type: 'Question-answer',
    title: 'Introduction to AI',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-04-03 00:00:00',
    location: 'Miami, Highland Ave',
  },
  {
    type: 'Question-answer',
    title: 'Startup Essentials',
    description: 'Essentials for launching a successful startup.',
    startOn: '2025-04-22 00:00:00',
    location: 'Los Angeles, Maple Ave',
  },
  {
    type: 'Question-answer',
    title: 'Startup Essentials',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-04-17 00:00:00',
    location: 'New York, Highland Ave',
  },
  {
    type: 'Conference',
    title: 'Networking Event',
    description: 'Join us for an insightful workshop on data science.',
    startOn: '2025-04-26 00:00:00',
    location: 'Los Angeles, Maple Ave',
  },
  {
    type: 'Webinar',
    title: 'Data Science Workshop',
    description: 'A networking event to meet industry experts.',
    startOn: '2025-04-01 00:00:00',
    location: 'Houston, Maple Ave',
  },
  {
    type: 'Meeting with an expert',
    title: 'Introduction to AI',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-04-25 00:00:00',
    location: 'Chicago, Broadway',
  },
  {
    type: 'Meeting with an expert',
    title: 'Data Science Workshop',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-04-02 00:00:00',
    location: 'Houston, Highland Ave',
  },
  {
    type: 'Webinar',
    title: 'Startup Essentials',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-04-08 00:00:00',
    location: 'Los Angeles, Highland Ave',
  },
  {
    type: 'Question-answer',
    title: 'Introduction to AI',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-04-03 00:00:00',
    location: 'New York, Highland Ave',
  },
  {
    type: 'Question-answer',
    title: 'Data Science Workshop',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-04-10 00:00:00',
    location: 'Miami, Maple Ave',
  },
  {
    type: 'Webinar',
    title: 'Data Science Workshop',
    description: 'Discuss the upcoming tech trends of 2024.',
    startOn: '2025-04-04 00:00:00',
    location: 'Los Angeles, Elm St',
  },
  {
    type: 'Conference',
    title: 'Data Science Workshop',
    description: 'Learn about the latest in AI technology.',
    startOn: '2025-04-19 00:00:00',
    location: 'Los Angeles, Elm St',
  },
  {
    type: 'Conference',
    title: 'Introduction to AI',
    description: 'A networking event to meet industry experts.',
    startOn: '2025-04-20 00:00:00',
    location: 'Houston, Main St',
  },
];
